fileList = {'CreateSupersocket.c', ...
    'InitializeSupersocket.c', ...
    'AddSocket.c', ...
    'SendData.c',...
    'PrintSupersocket.c', ...
    'ReceiveData.c',...
    'DiscoverSocket.c',...
    'InitializeSupersocketListener.c'};

if exist('target', 'var') && strcmp(target, 'windows')
    compilerVersion = '';
    linkedLibs      = '';
else
    compilerVersion = 'GCC=/usr/bin/gcc-4.9';
    linkedLibs = ['-L/usr/local/MATLAB/R2017b/sys/os/glnxa64/' ...
        '-L/usr/lib/x86_64-linux-gnu/'];
end
        
        
for ii=1:length(fileList)
    fprintf('Compiling: %s\n', fileList{ii});
    mex( ...
        '-silent', ...
        fileList{ii}, ...
        'SupersocketMatlabHeader.c', ...
    	compilerVersion, ...
        'CFLAGS="-std=c11 -fPIC -DMATLAB"', ...
        '-I../../../../Include/', ...
        '-L../../../../Include', ...
        linkedLibs, ...
        'LDFLAGS="\$LDFLAGS -Wl,-rpath,../../../../Include"', ...
        '-lmatlabsupersocket');
end